"""
Email sender for the museum kiosk: delivers the generated image to the
visitor's address via Gmail SMTP (or any SMTP provider).

Configuration (.env or Streamlit secrets):
    SMTP_USER      Gmail address (required)
    SMTP_PASSWORD  Gmail App Password — 16 characters, no spaces (required)
    SMTP_FROM      optional, defaults to SMTP_USER
    SMTP_HOST      optional, defaults to smtp.gmail.com
    SMTP_PORT      optional, defaults to 587 (STARTTLS)
    SMTP_USE_SSL   "1" to use SMTP_SSL on port 465; otherwise STARTTLS

See EMAIL_SETUP.md for the full Gmail account setup procedure.
"""

import os
import smtplib
from email.message import EmailMessage
from email.utils import formataddr, formatdate, make_msgid
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Display name shown to recipients; a named sender is trusted more than a
# bare address and improves inbox placement.
SENDER_NAME = "Future Transport — Bienne/Biel 2075"


def _get_secret(key: str, default: str = "") -> str:
    try:
        import streamlit as st
        return st.secrets[key]
    except Exception:
        return os.getenv(key, default)


EMAIL_TEMPLATES = {
    "fr": {
        "subject": "Votre vision du Zentralplatz en 2075",
        "body": (
            "Bonjour,\n\n"
            "Merci d'avoir visité l'exposition Future Transport — "
            "Bienne / Biel 2075, consacrée à l'avenir de la mobilité "
            "urbaine.\n\n"
            "Pendant votre visite, vous avez imaginé à quoi pourrait "
            "ressembler un lieu emblématique de Bienne dans 50 ans. "
            "Vous trouverez votre création ci-dessous et en pièce "
            "jointe, afin de pouvoir la conserver et la partager.\n\n"
            "Cette image a été générée par intelligence artificielle à "
            "partir de votre idée. Une sélection des visions des "
            "visiteurs sera présentée dans l'exposition.\n\n"
            "Au plaisir de vous revoir au musée,\n"
            "L'équipe Future Transport — Bienne / Biel 2075\n"
        ),
        "footer": (
            "Vous recevez cet email parce que vous l'avez demandé à la "
            "borne de l'exposition. Il s'agit d'un envoi unique : vous "
            "ne recevrez aucun autre message de notre part."
        ),
    },
    "de": {
        "subject": "Ihre Vision des Zentralplatzes im Jahr 2075",
        "body": (
            "Guten Tag,\n\n"
            "Vielen Dank für Ihren Besuch der Ausstellung Future "
            "Transport — Biel / Bienne 2075 über die Zukunft der "
            "urbanen Mobilität.\n\n"
            "Während Ihres Besuchs haben Sie sich vorgestellt, wie ein "
            "markanter Ort in Biel in 50 Jahren aussehen könnte. Ihre "
            "Kreation finden Sie unten und im Anhang, sodass Sie sie "
            "behalten und teilen können.\n\n"
            "Dieses Bild wurde von einer künstlichen Intelligenz auf "
            "Basis Ihrer Idee erzeugt. Eine Auswahl der Visionen der "
            "Besucherinnen und Besucher wird in der Ausstellung "
            "gezeigt.\n\n"
            "Wir freuen uns auf ein Wiedersehen im Museum,\n"
            "Das Team Future Transport — Biel / Bienne 2075\n"
        ),
        "footer": (
            "Sie erhalten diese E-Mail, weil Sie sie am Terminal der "
            "Ausstellung angefordert haben. Es handelt sich um einen "
            "einmaligen Versand: Sie erhalten keine weiteren Nachrichten "
            "von uns."
        ),
    },
    "en": {
        "subject": "Your vision of the Zentralplatz in 2075",
        "body": (
            "Hello,\n\n"
            "Thank you for visiting the Future Transport — "
            "Bienne / Biel 2075 exhibition on the future of urban "
            "mobility.\n\n"
            "During your visit, you imagined what an iconic place in "
            "Biel could look like in 50 years. You will find your "
            "creation below and attached, so you can keep it and share "
            "it.\n\n"
            "This image was generated by artificial intelligence based "
            "on your idea. A selection of visitors' visions will be "
            "shown in the exhibition.\n\n"
            "We hope to see you again at the museum,\n"
            "The Future Transport — Bienne / Biel 2075 team\n"
        ),
        "footer": (
            "You are receiving this email because you requested it at "
            "the exhibition kiosk. This is a one-time message: you will "
            "not receive any further emails from us."
        ),
    },
}


def _build_html(body: str, footer: str, image_cid: str) -> str:
    """Render the plain-text body as a styled HTML email with the image
    shown inline (referenced by Content-ID)."""
    paragraphs = "".join(
        f'<p style="margin:0 0 1em 0;">{p.strip().replace(chr(10), "<br>")}</p>'
        for p in body.strip().split("\n\n")
        if p.strip()
    )
    return f"""\
<!DOCTYPE html>
<html>
  <body style="margin:0;padding:24px;background:#f4f6f8;
               font-family:'Interstate',Arial,Helvetica,sans-serif;color:#222;">
    <div style="max-width:600px;margin:0 auto;background:#ffffff;
                border-radius:12px;padding:28px;
                font-family:'Interstate',Arial,Helvetica,sans-serif;">
      <p style="font-size:20px;font-weight:600;color:#28373b;
                margin:0 0 18px 0;">{SENDER_NAME}</p>
      <div style="font-size:15px;line-height:1.6;">{paragraphs}</div>
      <img src="cid:{image_cid}" alt="{SENDER_NAME}"
           style="width:100%;border-radius:8px;margin-top:8px;"/>
      <p style="font-size:12px;color:#8a93a0;line-height:1.5;margin-top:20px;
                border-top:1px solid #eceff2;padding-top:12px;">{footer}</p>
    </div>
  </body>
</html>"""


def _prepare_image(image_bytes: bytes) -> tuple[bytes, str, str]:
    """
    Down-convert the generated image to an optimized JPEG to keep the email
    light (a large PNG with little text is a strong spam signal).

    Returns (bytes, mime_subtype, file_extension). Falls back to the original
    PNG if Pillow is unavailable or conversion fails.
    """
    try:
        import io

        from PIL import Image

        with Image.open(io.BytesIO(image_bytes)) as img:
            img = img.convert("RGB")
            # The kiosk renders at 1024px; cap the longest side as a safeguard.
            img.thumbnail((1024, 1024))
            buf = io.BytesIO()
            img.save(buf, format="JPEG", quality=85, optimize=True)
        return buf.getvalue(), "jpeg", "jpg"
    except Exception:
        return image_bytes, "png", "png"


def is_configured() -> bool:
    """True if SMTP credentials are set and non-empty."""
    return bool(
        _get_secret("SMTP_USER")
        and _get_secret("SMTP_PASSWORD")
    )


def send_image_email(to_email: str, image_path: str, lang: str = "fr") -> None:
    """
    Send the generated image to the visitor.
    Raises RuntimeError if SMTP is not configured, smtplib.SMTPException
    on transport errors.
    """
    host = _get_secret("SMTP_HOST", "smtp.gmail.com") or "smtp.gmail.com"
    port_raw = _get_secret("SMTP_PORT", "587") or "587"
    port = int(port_raw)
    user = _get_secret("SMTP_USER")
    password = _get_secret("SMTP_PASSWORD")
    sender = _get_secret("SMTP_FROM") or user
    use_ssl = _get_secret("SMTP_USE_SSL", "0").strip() in ("1", "true", "True")

    if not (user and password):
        raise RuntimeError(
            "SMTP not configured. Set SMTP_USER and SMTP_PASSWORD in .env."
        )

    password = password.replace(" ", "")

    template = EMAIL_TEMPLATES.get(lang, EMAIL_TEMPLATES["fr"])
    sender_domain = sender.split("@")[-1] or "gmail.com"

    msg = EmailMessage()
    msg["From"] = formataddr((SENDER_NAME, sender))
    msg["To"] = to_email
    msg["Reply-To"] = sender
    msg["Subject"] = template["subject"]
    # Well-formed Date and Message-ID reduce the odds of being flagged.
    msg["Date"] = formatdate(localtime=True)
    msg["Message-ID"] = make_msgid(domain=sender_domain)
    # A List-Unsubscribe header lowers the spam score for automated mail.
    msg["List-Unsubscribe"] = f"<mailto:{sender}?subject=unsubscribe>"

    # Plain-text part (fallback) + HTML alternative with the image inline.
    msg.set_content(template["body"])

    img_path = Path(image_path)
    if img_path.exists():
        image_bytes, subtype, ext = _prepare_image(img_path.read_bytes())
        filename = f"{img_path.stem}.{ext}"
        image_cid = make_msgid(domain=sender_domain)
        msg.add_alternative(
            _build_html(template["body"], template["footer"], image_cid[1:-1]),
            subtype="html",
        )
        # Embed the image inside the HTML part (multipart/related).
        msg.get_payload()[1].add_related(
            image_bytes, maintype="image", subtype=subtype, cid=image_cid
        )
        # Also attach it so the visitor can download/keep the souvenir.
        msg.add_attachment(
            image_bytes,
            maintype="image",
            subtype=subtype,
            filename=filename,
        )

    if use_ssl:
        with smtplib.SMTP_SSL(host, port) as smtp:
            smtp.login(user, password)
            smtp.send_message(msg)
    else:
        with smtplib.SMTP(host, port) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()
            smtp.login(user, password)
            smtp.send_message(msg)
